site_name: 中国法定民政登记文档结构特征与智能化识别版式规范指南
site_url: https://readthedocs.io
theme:
  name: material
  custom_dir: overrides

nav:
  - 首页: index.md
    - 离婚登记文档外壳几何拓扑结构与计算机视觉 ROI 锚定规范: cmy.md
    - 离婚登记内页多模态语义网格与表格要素解构规范: inner.md
    - 登记文书多维频域特征、色彩空间重构与防伪多因子验证规范:  security.md
